tasks:
  - name: Setup
    init: |
      sudo apt-get update
      sudo apt-get install -y libgl1 libglib2.0-0 poppler-utils tesseract-ocr
      pip install -r requirements.txt

  - name: Run Flask
    command: python3 app.py
